// SPDX-License-Identifier: Apache-2.0

// Package braintest provides a contract test suite that any [brain.Store]
// implementation can run. Implementations call [RunContract] from a
// normal test function, handing over a factory that produces a fresh
// store per subtest and a [Capabilities] value describing which
// backend-specific behaviours apply.
//
// This is deliberately a non-_test.go package so multiple backends in
// different directories can import and run the same suite.
package braintest

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"testing"

	"github.com/jeffs-brain/memory/go/brain"
)

// Factory builds a fresh [brain.Store] for a single subtest. The returned
// cleanup function is called at the end of the subtest to release
// resources.
type Factory func(t *testing.T) (brain.Store, func())

// Capabilities describes which backend-specific behaviours the contract
// suite should exercise. Backends opt in to the cases that apply.
type Capabilities struct {
	// LocalPathAlwaysExists is true for backends whose LocalPath returns
	// a real on-disk path for every valid logical path (fs store, git
	// store). False for pure in-memory backends.
	LocalPathAlwaysExists bool

	// SupportsEmptyRepoBatch is true for git-backed stores that have to
	// handle a batch against a brand-new empty repository correctly
	// (rollback before the first commit). Pure in-memory and filesystem
	// backends do not need this test.
	SupportsEmptyRepoBatch bool
}

// RunContract executes the full contract suite against the store
// produced by factory. Each subtest gets its own fresh store. Caps
// enables backend-specific cases.
func RunContract(t *testing.T, factory Factory, caps Capabilities) {
	t.Helper()

	cases := []struct {
		name string
		fn   func(t *testing.T, store brain.Store)
	}{
		{"Read missing returns ErrNotFound", testReadMissing},
		{"Write then Read round-trips", testWriteRead},
		{"Write is idempotent overwrite", testWriteOverwrite},
		{"Write rejects invalid paths", testWriteInvalidPath},
		{"Append creates then extends", testAppend},
		{"Delete removes the file", testDelete},
		{"Delete missing returns ErrNotFound", testDeleteMissing},
		{"Exists reports presence", testExists},
		{"Stat returns size and modtime", testStat},
		{"Stat missing returns ErrNotFound", testStatMissing},
		{"Rename moves content", testRename},
		{"Rename over existing overwrites", testRenameOverExisting},
		{"Rename missing returns ErrNotFound", testRenameMissing},
		{"List empty prefix", testListEmpty},
		{"List returns sorted entries", testListSorted},
		{"List hides generated by default", testListGeneratedHidden},
		{"List includes generated when requested", testListGeneratedShown},
		{"List recursive walks subtree", testListRecursive},
		{"List non-recursive returns directories", testListShallowDirs},
		{"List applies glob filter", testListGlobFilter},
		{"Batch commits on success", testBatchCommit},
		{"Batch rolls back on error", testBatchRollback},
		{"Batch reads see pending writes", testBatchReadOwn},
		{"Batch Write then Write keeps latter content", testBatchWriteThenWrite},
		{"Batch Write then Delete cancels both", testBatchWriteThenDelete},
		{"Batch Write then Rename moves pending content", testBatchWriteThenRenameMoveContent},
		{"Batch Write then Rename into same path overwrites", testBatchWriteThenRenameSamePath},
		{"Batch Append then Rename moves appended result", testBatchAppendThenRename},
		{"Batch events fire after commit", testSubscribeAfterBatchCommit},
		{"Root-level files round-trip", testRootLevelFiles},
		{"Subscribe receives change events", testSubscribe},
		{"Unsubscribe stops events", testUnsubscribe},
		{"Close makes the store unusable", testClose},
		{"Close is idempotent", testCloseIdempotent},
		{"All ops return ErrReadOnly after Close", testErrReadOnlyAfterClose},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			store, cleanup := factory(t)
			defer cleanup()
			tc.fn(t, store)
		})
	}

	// Capability-gated cases.
	t.Run("List skips .git metadata", func(t *testing.T) {
		if !caps.LocalPathAlwaysExists {
			t.Skip("backend has no on-disk layout; .git filtering does not apply")
		}
		store, cleanup := factory(t)
		defer cleanup()
		testListSkipsGit(t, store)
	})

	t.Run("LocalPath semantics match backend", func(t *testing.T) {
		store, cleanup := factory(t)
		defer cleanup()
		testLocalPathSemantics(t, store, caps.LocalPathAlwaysExists)
	})

	if caps.SupportsEmptyRepoBatch {
		t.Run("Batch rollback in empty repo", func(t *testing.T) {
			store, cleanup := factory(t)
			defer cleanup()
			testBatchRollbackEmptyRepo(t, store)
		})
	}
}

// --- Helpers ---

func ctxFor(t *testing.T) context.Context {
	t.Helper()
	return t.Context()
}

func mustWrite(t *testing.T, s brain.Store, p brain.Path, body string) {
	t.Helper()
	if err := s.Write(ctxFor(t), p, []byte(body)); err != nil {
		t.Fatalf("Write(%q): %v", p, err)
	}
}

func mustRead(t *testing.T, s brain.Store, p brain.Path) []byte {
	t.Helper()
	data, err := s.Read(ctxFor(t), p)
	if err != nil {
		t.Fatalf("Read(%q): %v", p, err)
	}
	return data
}

// --- Tests ---

func testReadMissing(t *testing.T, s brain.Store) {
	_, err := s.Read(ctxFor(t), "memory/global/nope.md")
	if err == nil {
		t.Fatal("Read missing returned nil error")
	}
	if !errors.Is(err, brain.ErrNotFound) {
		t.Fatalf("error does not wrap ErrNotFound: %v", err)
	}
}

func testWriteRead(t *testing.T, s brain.Store) {
	p := brain.Path("memory/global/user-role.md")
	mustWrite(t, s, p, "Alex is a lead engineer")
	got := mustRead(t, s, p)
	if string(got) != "Alex is a lead engineer" {
		t.Fatalf("round trip mismatch: got %q", got)
	}
}

func testWriteOverwrite(t *testing.T, s brain.Store) {
	p := brain.Path("wiki/go/interfaces.md")
	mustWrite(t, s, p, "first")
	mustWrite(t, s, p, "second")
	if string(mustRead(t, s, p)) != "second" {
		t.Fatal("overwrite did not replace content")
	}
}

func testWriteInvalidPath(t *testing.T, s brain.Store) {
	err := s.Write(ctxFor(t), "../etc/passwd", []byte("nope"))
	if err == nil {
		t.Fatal("Write accepted invalid path")
	}
	if !errors.Is(err, brain.ErrInvalidPath) {
		t.Fatalf("error does not wrap ErrInvalidPath: %v", err)
	}
}

func testAppend(t *testing.T, s brain.Store) {
	p := brain.Path("wiki/_log.md")
	if err := s.Append(ctxFor(t), p, []byte("line one\n")); err != nil {
		t.Fatalf("Append (create): %v", err)
	}
	if err := s.Append(ctxFor(t), p, []byte("line two\n")); err != nil {
		t.Fatalf("Append (extend): %v", err)
	}
	got := mustRead(t, s, p)
	if string(got) != "line one\nline two\n" {
		t.Fatalf("append mismatch: got %q", got)
	}
}

func testDelete(t *testing.T, s brain.Store) {
	p := brain.Path("memory/global/tmp.md")
	mustWrite(t, s, p, "bye")
	if err := s.Delete(ctxFor(t), p); err != nil {
		t.Fatalf("Delete: %v", err)
	}
	exists, err := s.Exists(ctxFor(t), p)
	if err != nil {
		t.Fatalf("Exists after delete: %v", err)
	}
	if exists {
		t.Fatal("path still exists after delete")
	}
}

func testDeleteMissing(t *testing.T, s brain.Store) {
	err := s.Delete(ctxFor(t), "memory/global/never.md")
	if err == nil {
		t.Fatal("Delete missing returned nil error")
	}
	if !errors.Is(err, brain.ErrNotFound) {
		t.Fatalf("error does not wrap ErrNotFound: %v", err)
	}
}

func testExists(t *testing.T, s brain.Store) {
	p := brain.Path("memory/global/exists.md")
	exists, err := s.Exists(ctxFor(t), p)
	if err != nil {
		t.Fatalf("Exists pre: %v", err)
	}
	if exists {
		t.Fatal("Exists true before write")
	}
	mustWrite(t, s, p, "here")
	exists, err = s.Exists(ctxFor(t), p)
	if err != nil {
		t.Fatalf("Exists post: %v", err)
	}
	if !exists {
		t.Fatal("Exists false after write")
	}
}

func testStat(t *testing.T, s brain.Store) {
	p := brain.Path("memory/global/stat.md")
	mustWrite(t, s, p, "twelve bytes")
	info, err := s.Stat(ctxFor(t), p)
	if err != nil {
		t.Fatalf("Stat: %v", err)
	}
	if info.Size != 12 {
		t.Errorf("Size = %d, want 12", info.Size)
	}
	if info.ModTime.IsZero() {
		t.Error("ModTime is zero")
	}
	if info.Path != p {
		t.Errorf("Path = %q, want %q", info.Path, p)
	}
	if info.IsDir {
		t.Error("IsDir = true for a file")
	}
}

func testStatMissing(t *testing.T, s brain.Store) {
	_, err := s.Stat(ctxFor(t), "memory/global/nope.md")
	if !errors.Is(err, brain.ErrNotFound) {
		t.Fatalf("error does not wrap ErrNotFound: %v", err)
	}
}

func testRename(t *testing.T, s brain.Store) {
	src := brain.Path("raw/web/old.md")
	dst := brain.Path("raw/.sources/web/old.md")
	mustWrite(t, s, src, "content")
	if err := s.Rename(ctxFor(t), src, dst); err != nil {
		t.Fatalf("Rename: %v", err)
	}
	srcExists, _ := s.Exists(ctxFor(t), src)
	if srcExists {
		t.Fatal("src still exists after rename")
	}
	if string(mustRead(t, s, dst)) != "content" {
		t.Fatal("dst missing content after rename")
	}
}

func testRenameOverExisting(t *testing.T, s brain.Store) {
	src := brain.Path("wiki/go/new.md")
	dst := brain.Path("wiki/go/existing.md")
	mustWrite(t, s, src, "new")
	mustWrite(t, s, dst, "old")
	if err := s.Rename(ctxFor(t), src, dst); err != nil {
		t.Fatalf("Rename over existing: %v", err)
	}
	if string(mustRead(t, s, dst)) != "new" {
		t.Fatal("rename did not overwrite dst")
	}
}

func testRenameMissing(t *testing.T, s brain.Store) {
	err := s.Rename(ctxFor(t), "memory/global/nope.md", "memory/global/other.md")
	if !errors.Is(err, brain.ErrNotFound) {
		t.Fatalf("error does not wrap ErrNotFound: %v", err)
	}
}

func testListEmpty(t *testing.T, s brain.Store) {
	entries, err := s.List(ctxFor(t), "memory/global", brain.ListOpts{})
	if err != nil {
		t.Fatalf("List: %v", err)
	}
	if len(entries) != 0 {
		t.Fatalf("List of empty prefix returned %d entries, want 0", len(entries))
	}
}

func testListSorted(t *testing.T, s brain.Store) {
	mustWrite(t, s, "memory/global/charlie.md", "c")
	mustWrite(t, s, "memory/global/alpha.md", "a")
	mustWrite(t, s, "memory/global/bravo.md", "b")

	entries, err := s.List(ctxFor(t), "memory/global", brain.ListOpts{})
	if err != nil {
		t.Fatalf("List: %v", err)
	}
	if len(entries) != 3 {
		t.Fatalf("List returned %d entries, want 3", len(entries))
	}
	want := []brain.Path{
		"memory/global/alpha.md",
		"memory/global/bravo.md",
		"memory/global/charlie.md",
	}
	for i, e := range entries {
		if e.Path != want[i] {
			t.Errorf("entries[%d].Path = %q, want %q", i, e.Path, want[i])
		}
	}
}

func testListGeneratedHidden(t *testing.T, s brain.Store) {
	mustWrite(t, s, "wiki/_index.md", "master")
	mustWrite(t, s, "wiki/article.md", "content")

	entries, err := s.List(ctxFor(t), "wiki", brain.ListOpts{})
	if err != nil {
		t.Fatalf("List: %v", err)
	}
	for _, e := range entries {
		if e.Path == "wiki/_index.md" {
			t.Fatal("default listing returned generated file")
		}
	}
}

func testListGeneratedShown(t *testing.T, s brain.Store) {
	mustWrite(t, s, "wiki/_index.md", "master")
	mustWrite(t, s, "wiki/article.md", "content")

	entries, err := s.List(ctxFor(t), "wiki", brain.ListOpts{IncludeGenerated: true})
	if err != nil {
		t.Fatalf("List: %v", err)
	}
	var gotGenerated bool
	for _, e := range entries {
		if e.Path == "wiki/_index.md" {
			gotGenerated = true
		}
	}
	if !gotGenerated {
		t.Fatal("List did not return generated file when requested")
	}
}

func testListRecursive(t *testing.T, s brain.Store) {
	mustWrite(t, s, "wiki/go/interfaces.md", "i")
	mustWrite(t, s, "wiki/go/generics.md", "g")
	mustWrite(t, s, "wiki/rust/traits.md", "t")

	entries, err := s.List(ctxFor(t), "wiki", brain.ListOpts{Recursive: true})
	if err != nil {
		t.Fatalf("List: %v", err)
	}
	var got []brain.Path
	for _, e := range entries {
		if !e.IsDir {
			got = append(got, e.Path)
		}
	}
	want := []brain.Path{
		"wiki/go/generics.md",
		"wiki/go/interfaces.md",
		"wiki/rust/traits.md",
	}
	if len(got) != len(want) {
		t.Fatalf("got %v, want %v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("entry[%d] = %q, want %q", i, got[i], want[i])
		}
	}
}

func testListShallowDirs(t *testing.T, s brain.Store) {
	mustWrite(t, s, "wiki/go/interfaces.md", "i")
	mustWrite(t, s, "wiki/rust/traits.md", "t")
	mustWrite(t, s, "wiki/top.md", "top")

	entries, err := s.List(ctxFor(t), "wiki", brain.ListOpts{})
	if err != nil {
		t.Fatalf("List: %v", err)
	}
	var gotDirs int
	var gotFiles int
	for _, e := range entries {
		if e.IsDir {
			gotDirs++
		} else {
			gotFiles++
		}
	}
	if gotDirs != 2 {
		t.Errorf("want 2 dirs, got %d", gotDirs)
	}
	if gotFiles != 1 {
		t.Errorf("want 1 file, got %d", gotFiles)
	}
}

func testListGlobFilter(t *testing.T, s brain.Store) {
	mustWrite(t, s, "wiki/go/a.md", "A")
	mustWrite(t, s, "wiki/go/b.txt", "B")
	mustWrite(t, s, "wiki/go/c.md", "C")

	entries, err := s.List(ctxFor(t), "wiki/go", brain.ListOpts{Glob: "*.md"})
	if err != nil {
		t.Fatalf("List: %v", err)
	}
	var names []brain.Path
	for _, e := range entries {
		names = append(names, e.Path)
	}
	want := []brain.Path{"wiki/go/a.md", "wiki/go/c.md"}
	if len(names) != len(want) {
		t.Fatalf("glob filter returned %v, want %v", names, want)
	}
	for i := range want {
		if names[i] != want[i] {
			t.Errorf("entry[%d] = %q, want %q", i, names[i], want[i])
		}
	}
}

func testBatchCommit(t *testing.T, s brain.Store) {
	err := s.Batch(ctxFor(t), brain.BatchOptions{Reason: "test"}, func(b brain.Batch) error {
		if err := b.Write(ctxFor(t), "memory/global/a.md", []byte("one")); err != nil {
			return err
		}
		if err := b.Write(ctxFor(t), "memory/global/b.md", []byte("two")); err != nil {
			return err
		}
		return nil
	})
	if err != nil {
		t.Fatalf("Batch: %v", err)
	}
	if string(mustRead(t, s, "memory/global/a.md")) != "one" {
		t.Error("a.md not written")
	}
	if string(mustRead(t, s, "memory/global/b.md")) != "two" {
		t.Error("b.md not written")
	}
}

func testBatchRollback(t *testing.T, s brain.Store) {
	mustWrite(t, s, "memory/global/existing.md", "original")

	sentinel := errors.New("abort")
	err := s.Batch(ctxFor(t), brain.BatchOptions{Reason: "test"}, func(b brain.Batch) error {
		if err := b.Write(ctxFor(t), "memory/global/new.md", []byte("should not survive")); err != nil {
			return err
		}
		if err := b.Write(ctxFor(t), "memory/global/existing.md", []byte("should not overwrite")); err != nil {
			return err
		}
		return sentinel
	})
	if !errors.Is(err, sentinel) {
		t.Fatalf("expected sentinel error, got %v", err)
	}
	exists, _ := s.Exists(ctxFor(t), "memory/global/new.md")
	if exists {
		t.Error("new file survived rolled-back batch")
	}
	got := mustRead(t, s, "memory/global/existing.md")
	if string(got) != "original" {
		t.Errorf("existing file modified by rolled-back batch: got %q", got)
	}
}

func testBatchReadOwn(t *testing.T, s brain.Store) {
	mustWrite(t, s, "memory/global/base.md", "base")

	err := s.Batch(ctxFor(t), brain.BatchOptions{Reason: "test"}, func(b brain.Batch) error {
		if err := b.Write(ctxFor(t), "memory/global/base.md", []byte("updated")); err != nil {
			return err
		}
		data, err := b.Read(ctxFor(t), "memory/global/base.md")
		if err != nil {
			return err
		}
		if string(data) != "updated" {
			t.Errorf("batch read did not see pending write: got %q", data)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("Batch: %v", err)
	}
}

func testBatchWriteThenWrite(t *testing.T, s brain.Store) {
	// Within a batch, the latter Write to the same path must win. This is
	// the documented "Write followed by Write keeps the latter content"
	// contract clause.
	p := brain.Path("memory/global/overwrite.md")
	err := s.Batch(ctxFor(t), brain.BatchOptions{Reason: "test"}, func(b brain.Batch) error {
		if err := b.Write(ctxFor(t), p, []byte("first")); err != nil {
			return err
		}
		return b.Write(ctxFor(t), p, []byte("second"))
	})
	if err != nil {
		t.Fatalf("Batch: %v", err)
	}
	got := string(mustRead(t, s, p))
	if got != "second" {
		t.Errorf("content = %q, want %q (latter Write must win)", got, "second")
	}
}

func testBatchWriteThenDelete(t *testing.T, s brain.Store) {
	// Write followed by Delete on the same path within one batch should
	// cancel both: the file must not exist after commit and no error is
	// surfaced because the batch saw the write first.
	err := s.Batch(ctxFor(t), brain.BatchOptions{Reason: "test"}, func(b brain.Batch) error {
		p := brain.Path("memory/global/ephemeral.md")
		if err := b.Write(ctxFor(t), p, []byte("A")); err != nil {
			return err
		}
		return b.Delete(ctxFor(t), p)
	})
	if err != nil {
		t.Fatalf("Batch: %v", err)
	}
	exists, err := s.Exists(ctxFor(t), "memory/global/ephemeral.md")
	if err != nil {
		t.Fatalf("Exists: %v", err)
	}
	if exists {
		t.Fatal("Write+Delete combo left a file behind")
	}
}

func testBatchWriteThenRenameMoveContent(t *testing.T, s brain.Store) {
	// Write a pending file and rename it within the same batch. The
	// destination must carry the pending content.
	err := s.Batch(ctxFor(t), brain.BatchOptions{Reason: "test"}, func(b brain.Batch) error {
		src := brain.Path("memory/global/pending-src.md")
		dst := brain.Path("memory/global/pending-dst.md")
		if err := b.Write(ctxFor(t), src, []byte("A")); err != nil {
			return err
		}
		return b.Rename(ctxFor(t), src, dst)
	})
	if err != nil {
		t.Fatalf("Batch: %v", err)
	}
	if srcExists, _ := s.Exists(ctxFor(t), "memory/global/pending-src.md"); srcExists {
		t.Error("source still present after Write+Rename combo")
	}
	got := string(mustRead(t, s, "memory/global/pending-dst.md"))
	if got != "A" {
		t.Errorf("destination content = %q, want %q", got, "A")
	}
}

func testBatchWriteThenRenameSamePath(t *testing.T, s brain.Store) {
	// Write to dst, then rename another path into dst. The rename should
	// win: the pending write content is replaced by the renamed source.
	mustWrite(t, s, "memory/global/renamesrc.md", "FROM-RENAME")

	err := s.Batch(ctxFor(t), brain.BatchOptions{Reason: "test"}, func(b brain.Batch) error {
		dst := brain.Path("memory/global/renamedst.md")
		if err := b.Write(ctxFor(t), dst, []byte("FROM-WRITE")); err != nil {
			return err
		}
		return b.Rename(ctxFor(t), "memory/global/renamesrc.md", dst)
	})
	if err != nil {
		t.Fatalf("Batch: %v", err)
	}
	got := string(mustRead(t, s, "memory/global/renamedst.md"))
	if got != "FROM-RENAME" {
		t.Errorf("dst content = %q, want %q", got, "FROM-RENAME")
	}
}

func testBatchAppendThenRename(t *testing.T, s brain.Store) {
	// Append then Rename inside the same batch: the appended result must
	// land at the destination.
	mustWrite(t, s, "memory/global/log.md", "base\n")

	err := s.Batch(ctxFor(t), brain.BatchOptions{Reason: "test"}, func(b brain.Batch) error {
		src := brain.Path("memory/global/log.md")
		dst := brain.Path("memory/global/log-rotated.md")
		if err := b.Append(ctxFor(t), src, []byte("extra\n")); err != nil {
			return err
		}
		return b.Rename(ctxFor(t), src, dst)
	})
	if err != nil {
		t.Fatalf("Batch: %v", err)
	}
	if srcExists, _ := s.Exists(ctxFor(t), "memory/global/log.md"); srcExists {
		t.Error("source still present after Append+Rename combo")
	}
	got := string(mustRead(t, s, "memory/global/log-rotated.md"))
	if got != "base\nextra\n" {
		t.Errorf("destination content = %q, want %q", got, "base\nextra\n")
	}
}

func testSubscribeAfterBatchCommit(t *testing.T, s brain.Store) {
	// Events from a batch must fire after commit, never during the user
	// callback. We assert by recording the count at each step.
	var duringCallback int
	var finalCount int
	unsub := s.Subscribe(brain.EventSinkFunc(func(evt brain.ChangeEvent) {
		finalCount++
	}))
	defer unsub()

	err := s.Batch(ctxFor(t), brain.BatchOptions{Reason: "test"}, func(b brain.Batch) error {
		if err := b.Write(ctxFor(t), "memory/global/e1.md", []byte("one")); err != nil {
			return err
		}
		if err := b.Write(ctxFor(t), "memory/global/e2.md", []byte("two")); err != nil {
			return err
		}
		duringCallback = finalCount
		return nil
	})
	if err != nil {
		t.Fatalf("Batch: %v", err)
	}
	if duringCallback != 0 {
		t.Errorf("events fired during batch callback: %d", duringCallback)
	}
	if finalCount < 2 {
		t.Errorf("final event count = %d, want at least 2", finalCount)
	}
}

func testRootLevelFiles(t *testing.T, s brain.Store) {
	// Root-level files (kb-schema.md, schema-version.yaml) must be
	// writable, readable, and round-trip correctly through every backend.
	// This catches path-resolution gaps where a new root-level file is
	// defined in paths.go but not handled by the store's mapping layer.
	rootFiles := []struct {
		path brain.Path
		body string
	}{
		{brain.Schema(), "# KB Schema\n"},
		{brain.SchemaVersionPath(), "version: 1\n"},
	}
	for _, rf := range rootFiles {
		mustWrite(t, s, rf.path, rf.body)
		got := string(mustRead(t, s, rf.path))
		if got != rf.body {
			t.Errorf("%s: round-trip mismatch: got %q, want %q", rf.path, got, rf.body)
		}
		exists, err := s.Exists(ctxFor(t), rf.path)
		if err != nil {
			t.Fatalf("%s: Exists: %v", rf.path, err)
		}
		if !exists {
			t.Errorf("%s: Exists returned false after write", rf.path)
		}
	}
}

func testSubscribe(t *testing.T, s brain.Store) {
	var received []brain.ChangeEvent
	unsub := s.Subscribe(brain.EventSinkFunc(func(evt brain.ChangeEvent) {
		received = append(received, evt)
	}))
	defer unsub()

	mustWrite(t, s, "memory/global/foo.md", "hello")

	if len(received) != 1 {
		t.Fatalf("want 1 event, got %d", len(received))
	}
	if received[0].Path != "memory/global/foo.md" {
		t.Errorf("event path = %q, want memory/global/foo.md", received[0].Path)
	}
	if received[0].Kind != brain.ChangeCreated {
		t.Errorf("event kind = %v, want ChangeCreated", received[0].Kind)
	}
}

func testUnsubscribe(t *testing.T, s brain.Store) {
	var count int
	unsub := s.Subscribe(brain.EventSinkFunc(func(evt brain.ChangeEvent) {
		count++
	}))

	mustWrite(t, s, "memory/global/a.md", "1")
	unsub()
	mustWrite(t, s, "memory/global/b.md", "2")

	if count != 1 {
		t.Fatalf("want 1 event before unsubscribe, got %d", count)
	}
}

func testClose(t *testing.T, s brain.Store) {
	if err := s.Close(); err != nil {
		t.Fatalf("Close: %v", err)
	}
	err := s.Write(ctxFor(t), "memory/global/after.md", []byte("nope"))
	if !errors.Is(err, brain.ErrReadOnly) {
		t.Fatalf("want ErrReadOnly after Close, got %v", err)
	}
}

func testCloseIdempotent(t *testing.T, s brain.Store) {
	if err := s.Close(); err != nil {
		t.Fatalf("first Close: %v", err)
	}
	if err := s.Close(); err != nil {
		t.Fatalf("second Close: %v", err)
	}
}

func testErrReadOnlyAfterClose(t *testing.T, s brain.Store) {
	mustWrite(t, s, "memory/global/before.md", "ok")
	if err := s.Close(); err != nil {
		t.Fatalf("Close: %v", err)
	}
	ctx := ctxFor(t)
	checks := []struct {
		name string
		fn   func() error
	}{
		{"Read", func() error { _, err := s.Read(ctx, "memory/global/before.md"); return err }},
		{"Write", func() error { return s.Write(ctx, "memory/global/x.md", []byte("x")) }},
		{"Append", func() error { return s.Append(ctx, "memory/global/y.md", []byte("y")) }},
		{"Delete", func() error { return s.Delete(ctx, "memory/global/before.md") }},
		{"Rename", func() error { return s.Rename(ctx, "memory/global/before.md", "memory/global/after.md") }},
		{"Exists", func() error { _, err := s.Exists(ctx, "memory/global/before.md"); return err }},
		{"Stat", func() error { _, err := s.Stat(ctx, "memory/global/before.md"); return err }},
		{"List", func() error { _, err := s.List(ctx, "memory/global", brain.ListOpts{}); return err }},
		{"Batch", func() error {
			return s.Batch(ctx, brain.BatchOptions{}, func(b brain.Batch) error { return nil })
		}},
	}
	for _, c := range checks {
		err := c.fn()
		if !errors.Is(err, brain.ErrReadOnly) {
			t.Errorf("%s after Close: want ErrReadOnly, got %v", c.name, err)
		}
	}
}

func testListSkipsGit(t *testing.T, s brain.Store) {
	// Backends that sit on a real directory must hide the git metadata
	// tree from List results even when a recursive walk sweeps over it.
	mustWrite(t, s, "wiki/visible.md", "ok")
	localRoot, ok := s.LocalPath("wiki/visible.md")
	if !ok {
		t.Fatal("LocalPath missing for a backend that claims LocalPathAlwaysExists")
	}
	// Walk up to the brain root (parent of wiki/) and plant a .git
	// directory with a bogus file inside to prove List skips it.
	wikiDir := filepath.Dir(localRoot)
	brainRoot := filepath.Dir(wikiDir)
	gitDir := filepath.Join(brainRoot, ".git")
	if err := os.MkdirAll(filepath.Join(gitDir, "objects"), 0o755); err != nil {
		t.Fatalf("mkdir .git: %v", err)
	}
	if err := os.WriteFile(filepath.Join(gitDir, "HEAD"), []byte("ref: refs/heads/main\n"), 0o644); err != nil {
		t.Fatalf("write .git/HEAD: %v", err)
	}

	entries, err := s.List(ctxFor(t), "", brain.ListOpts{Recursive: true})
	if err != nil {
		t.Fatalf("List: %v", err)
	}
	for _, e := range entries {
		ps := string(e.Path)
		if ps == ".git" || ps == ".git/HEAD" || hasPrefix(ps, ".git/") {
			t.Errorf("List returned git metadata entry: %q", ps)
		}
	}
}

func testLocalPathSemantics(t *testing.T, s brain.Store, alwaysExists bool) {
	p := brain.Path("memory/global/local-path.md")
	mustWrite(t, s, p, "x")
	path, ok := s.LocalPath(p)
	if alwaysExists {
		if !ok {
			t.Fatalf("LocalPath(%q) returned ok=false for a filesystem-backed store", p)
		}
		if path == "" {
			t.Fatalf("LocalPath(%q) returned empty path despite ok=true", p)
		}
		if !filepath.IsAbs(path) {
			t.Errorf("LocalPath returned non-absolute path: %q", path)
		}
	} else {
		if ok {
			t.Errorf("LocalPath(%q) returned ok=true for a backend with no on-disk layout", p)
		}
		if path != "" {
			t.Errorf("LocalPath(%q) returned %q, want empty", p, path)
		}
	}
}

func testBatchRollbackEmptyRepo(t *testing.T, s brain.Store) {
	// On a brand-new git store with no commits yet, a failing batch must
	// leave the working tree empty and not create a commit.
	sentinel := errors.New("abort")
	err := s.Batch(ctxFor(t), brain.BatchOptions{Reason: "test"}, func(b brain.Batch) error {
		if err := b.Write(ctxFor(t), "memory/global/first.md", []byte("should not survive")); err != nil {
			return err
		}
		return sentinel
	})
	if !errors.Is(err, sentinel) {
		t.Fatalf("want sentinel error, got %v", err)
	}
	exists, err := s.Exists(ctxFor(t), "memory/global/first.md")
	if err != nil {
		t.Fatalf("Exists: %v", err)
	}
	if exists {
		t.Error("rolled-back file survived in empty-repo batch")
	}
}

func hasPrefix(s, prefix string) bool {
	if len(s) < len(prefix) {
		return false
	}
	return s[:len(prefix)] == prefix
}
