// SPDX-License-Identifier: Apache-2.0

import { mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { ErrInvalidPath, ErrNotFound, ErrReadOnly } from './errors.js'
import { createFsStore } from './fsstore.js'
import { createGitStore } from './gitstore.js'
import type { Store } from './index.js'
import { createMemStore } from './memstore.js'
import { type Path, toPath } from './path.js'

type Factory = {
  name: string
  create: () => Promise<{ store: Store; cleanup: () => Promise<void> }>
  supportsLocalPath: boolean
}

const factories: Factory[] = [
  {
    name: 'memstore',
    supportsLocalPath: false,
    create: async () => {
      const store = createMemStore()
      return { store, cleanup: async () => store.close() }
    },
  },
  {
    name: 'fsstore',
    supportsLocalPath: true,
    create: async () => {
      const dir = await mkdtemp(join(tmpdir(), 'memory-fsstore-'))
      const store = await createFsStore({ root: dir })
      return {
        store,
        cleanup: async () => {
          await store.close()
          await rm(dir, { recursive: true, force: true })
        },
      }
    },
  },
  {
    name: 'gitstore',
    supportsLocalPath: true,
    create: async () => {
      const dir = await mkdtemp(join(tmpdir(), 'memory-gitstore-'))
      const store = await createGitStore({ dir, init: true })
      return {
        store,
        cleanup: async () => {
          await store.close()
          await rm(dir, { recursive: true, force: true })
        },
      }
    },
  },
]

const buf = (s: string): Buffer => Buffer.from(s, 'utf8')
const p = (s: string): Path => toPath(s)

for (const factory of factories) {
  describe(`Store contract: ${factory.name}`, () => {
    let store: Store
    let cleanup: () => Promise<void>

    beforeEach(async () => {
      const created = await factory.create()
      store = created.store
      cleanup = created.cleanup
    })

    afterEach(async () => {
      await cleanup()
    })

    it('read missing throws ErrNotFound', async () => {
      await expect(store.read(p('memory/nope.md'))).rejects.toBeInstanceOf(ErrNotFound)
    })

    it('write then read round-trips', async () => {
      await store.write(p('memory/a.md'), buf('hello'))
      const got = await store.read(p('memory/a.md'))
      expect(got.toString()).toBe('hello')
    })

    it('write overwrites existing content', async () => {
      await store.write(p('wiki/doc.md'), buf('first'))
      await store.write(p('wiki/doc.md'), buf('second'))
      expect((await store.read(p('wiki/doc.md'))).toString()).toBe('second')
    })

    it('append creates then extends', async () => {
      await store.append(p('wiki/log.md'), buf('a\n'))
      await store.append(p('wiki/log.md'), buf('b\n'))
      expect((await store.read(p('wiki/log.md'))).toString()).toBe('a\nb\n')
    })

    it('delete removes the file', async () => {
      await store.write(p('memory/tmp.md'), buf('bye'))
      await store.delete(p('memory/tmp.md'))
      expect(await store.exists(p('memory/tmp.md'))).toBe(false)
    })

    it('delete missing throws ErrNotFound', async () => {
      await expect(store.delete(p('memory/never.md'))).rejects.toBeInstanceOf(ErrNotFound)
    })

    it('rename moves content', async () => {
      await store.write(p('raw/old.md'), buf('content'))
      await store.rename(p('raw/old.md'), p('raw/new.md'))
      expect(await store.exists(p('raw/old.md'))).toBe(false)
      expect((await store.read(p('raw/new.md'))).toString()).toBe('content')
    })

    it('rename over existing overwrites', async () => {
      await store.write(p('wiki/src.md'), buf('new'))
      await store.write(p('wiki/dst.md'), buf('old'))
      await store.rename(p('wiki/src.md'), p('wiki/dst.md'))
      expect((await store.read(p('wiki/dst.md'))).toString()).toBe('new')
    })

    it('rename missing throws ErrNotFound', async () => {
      await expect(store.rename(p('memory/nope.md'), p('memory/other.md'))).rejects.toBeInstanceOf(
        ErrNotFound,
      )
    })

    it('stat returns size and modtime', async () => {
      await store.write(p('memory/stat.md'), buf('twelve bytes'))
      const info = await store.stat(p('memory/stat.md'))
      expect(info.size).toBe(12)
      expect(info.isDir).toBe(false)
      expect(info.path).toBe('memory/stat.md')
    })

    it('list flat returns sorted children', async () => {
      await store.write(p('memory/c.md'), buf('c'))
      await store.write(p('memory/a.md'), buf('a'))
      await store.write(p('memory/b.md'), buf('b'))
      const out = await store.list(p('memory'))
      expect(out.map((e) => e.path)).toEqual(['memory/a.md', 'memory/b.md', 'memory/c.md'])
    })

    it('list hides generated by default', async () => {
      await store.write(p('wiki/_index.md'), buf('idx'))
      await store.write(p('wiki/article.md'), buf('body'))
      const out = await store.list(p('wiki'))
      expect(out.map((e) => e.path)).not.toContain('wiki/_index.md')
    })

    it('list includes generated when requested', async () => {
      await store.write(p('wiki/_index.md'), buf('idx'))
      await store.write(p('wiki/article.md'), buf('body'))
      const out = await store.list(p('wiki'), { includeGenerated: true })
      expect(out.map((e) => e.path)).toContain('wiki/_index.md')
    })

    it('list recursive walks subtree', async () => {
      await store.write(p('wiki/go/a.md'), buf('a'))
      await store.write(p('wiki/go/b.md'), buf('b'))
      await store.write(p('wiki/rust/c.md'), buf('c'))
      const out = await store.list(p('wiki'), { recursive: true })
      const files = out.filter((e) => !e.isDir).map((e) => e.path)
      expect(files).toEqual(['wiki/go/a.md', 'wiki/go/b.md', 'wiki/rust/c.md'])
    })

    it('list non-recursive returns directory entries', async () => {
      await store.write(p('wiki/go/a.md'), buf('a'))
      await store.write(p('wiki/top.md'), buf('t'))
      const out = await store.list(p('wiki'))
      const dirs = out.filter((e) => e.isDir)
      const files = out.filter((e) => !e.isDir)
      expect(dirs.map((e) => e.path)).toEqual(['wiki/go'])
      expect(files.map((e) => e.path)).toEqual(['wiki/top.md'])
    })

    it('list applies glob filter on base names', async () => {
      await store.write(p('wiki/a.md'), buf('a'))
      await store.write(p('wiki/b.txt'), buf('b'))
      await store.write(p('wiki/c.md'), buf('c'))
      const out = await store.list(p('wiki'), { glob: '*.md' })
      expect(out.map((e) => e.path)).toEqual(['wiki/a.md', 'wiki/c.md'])
    })

    it('batch commits on success', async () => {
      await store.batch({ reason: 'test' }, async (b) => {
        await b.write(p('memory/x.md'), buf('one'))
        await b.write(p('memory/y.md'), buf('two'))
      })
      expect((await store.read(p('memory/x.md'))).toString()).toBe('one')
      expect((await store.read(p('memory/y.md'))).toString()).toBe('two')
    })

    it('batch rolls back on error leaving brain untouched', async () => {
      await store.write(p('memory/keep.md'), buf('original'))
      const sentinel = new Error('abort')
      await expect(
        store.batch({ reason: 'test' }, async (b) => {
          await b.write(p('memory/new.md'), buf('nope'))
          await b.write(p('memory/keep.md'), buf('clobber'))
          throw sentinel
        }),
      ).rejects.toBe(sentinel)
      expect(await store.exists(p('memory/new.md'))).toBe(false)
      expect((await store.read(p('memory/keep.md'))).toString()).toBe('original')
    })

    it('batch reads see pending writes', async () => {
      await store.write(p('memory/base.md'), buf('base'))
      let seen = ''
      await store.batch({ reason: 'test' }, async (b) => {
        await b.write(p('memory/base.md'), buf('updated'))
        seen = (await b.read(p('memory/base.md'))).toString()
      })
      expect(seen).toBe('updated')
    })

    it('batch write then delete cancels both', async () => {
      await store.batch({ reason: 'test' }, async (b) => {
        await b.write(p('memory/ephem.md'), buf('A'))
        await b.delete(p('memory/ephem.md'))
      })
      expect(await store.exists(p('memory/ephem.md'))).toBe(false)
    })

    it('batch write then write keeps latter', async () => {
      await store.batch({ reason: 'test' }, async (b) => {
        await b.write(p('memory/ow.md'), buf('first'))
        await b.write(p('memory/ow.md'), buf('second'))
      })
      expect((await store.read(p('memory/ow.md'))).toString()).toBe('second')
    })

    it('batch write then rename moves pending content', async () => {
      await store.batch({ reason: 'test' }, async (b) => {
        await b.write(p('memory/src.md'), buf('A'))
        await b.rename(p('memory/src.md'), p('memory/dst.md'))
      })
      expect(await store.exists(p('memory/src.md'))).toBe(false)
      expect((await store.read(p('memory/dst.md'))).toString()).toBe('A')
    })

    it('batch append then rename moves appended result', async () => {
      await store.write(p('memory/log.md'), buf('base\n'))
      await store.batch({ reason: 'test' }, async (b) => {
        await b.append(p('memory/log.md'), buf('extra\n'))
        await b.rename(p('memory/log.md'), p('memory/log-rot.md'))
      })
      expect(await store.exists(p('memory/log.md'))).toBe(false)
      expect((await store.read(p('memory/log-rot.md'))).toString()).toBe('base\nextra\n')
    })

    it('subscribe receives change events after commit', async () => {
      const seen: string[] = []
      const unsub = store.subscribe((evt) => seen.push(`${evt.kind}:${evt.path}`))
      let duringCount = 0
      await store.batch({ reason: 'test' }, async (b) => {
        await b.write(p('memory/e1.md'), buf('one'))
        await b.write(p('memory/e2.md'), buf('two'))
        duringCount = seen.length
      })
      unsub()
      expect(duringCount).toBe(0)
      expect(seen.length).toBeGreaterThanOrEqual(2)
    })

    it('unsubscribe stops events', async () => {
      let count = 0
      const unsub = store.subscribe(() => {
        count++
      })
      await store.write(p('memory/a.md'), buf('1'))
      unsub()
      await store.write(p('memory/b.md'), buf('2'))
      expect(count).toBe(1)
    })

    it('concurrent writes do not corrupt', async () => {
      await Promise.all(
        Array.from({ length: 20 }, (_, i) => store.write(p(`memory/race-${i}.md`), buf(`v${i}`))),
      )
      for (let i = 0; i < 20; i++) {
        expect((await store.read(p(`memory/race-${i}.md`))).toString()).toBe(`v${i}`)
      }
    })

    it('rejects invalid paths: traversal', async () => {
      await expect(store.write('../etc/passwd' as Path, buf('x'))).rejects.toBeInstanceOf(
        ErrInvalidPath,
      )
    })

    it('rejects invalid paths: leading slash', async () => {
      await expect(store.write('/absolute.md' as Path, buf('x'))).rejects.toBeInstanceOf(
        ErrInvalidPath,
      )
    })

    it('rejects invalid paths: trailing slash', async () => {
      await expect(store.write('memory/dir/' as Path, buf('x'))).rejects.toBeInstanceOf(
        ErrInvalidPath,
      )
    })

    it('rejects invalid paths: null byte', async () => {
      await expect(store.write('memory/a\0b.md' as Path, buf('x'))).rejects.toBeInstanceOf(
        ErrInvalidPath,
      )
    })

    it('close makes the store unusable', async () => {
      await store.close()
      await expect(store.write(p('memory/a.md'), buf('x'))).rejects.toBeInstanceOf(ErrReadOnly)
    })

    it('close is idempotent', async () => {
      await store.close()
      await expect(store.close()).resolves.toBeUndefined()
    })

    it('localPath matches backend capability', async () => {
      await store.write(p('memory/lp.md'), buf('x'))
      const lp = store.localPath(p('memory/lp.md'))
      if (factory.supportsLocalPath) {
        expect(typeof lp).toBe('string')
        expect(lp).not.toBe('')
      } else {
        expect(lp).toBeUndefined()
      }
    })
  })
}
