// SPDX-License-Identifier: Apache-2.0

package storeutil

import (
	"errors"
	"fmt"
	iofs "io/fs"
	"os"
	"path/filepath"
	"sort"

	"github.com/jeffs-brain/memory/go/brain"
)

// List walks the working tree under dir and returns the logical file
// entries that match opts. absRoot is the absolute on-disk root, absDir
// is the absolute directory to list (use absRoot when dir is empty),
// and dir is the logical [brain.Path] passed to the store's List for
// error context.
//
// The walker honours [ShouldSkipDir] / [ShouldSkipFile] to hide backend
// metadata (.git, atomic staging areas). Entries that are marked as
// generated by [brain.IsGenerated] are filtered unless IncludeGenerated
// is set. Results are sorted by logical path.
func List(absRoot, absDir string, dir brain.Path, opts brain.ListOpts) ([]brain.FileInfo, error) {
	info, err := os.Stat(absDir)
	if errors.Is(err, iofs.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	if !info.IsDir() {
		return nil, fmt.Errorf("list %s: not a directory", dir)
	}

	var entries []brain.FileInfo
	if opts.Recursive {
		err = filepath.WalkDir(absDir, func(p string, d iofs.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if d.IsDir() {
				if ShouldSkipDir(d.Name()) {
					return iofs.SkipDir
				}
				return nil
			}
			if ShouldSkipFile(d.Name()) {
				return nil
			}
			relFS, relErr := filepath.Rel(absRoot, p)
			if relErr != nil {
				return relErr
			}
			logical := LogicalFromRel(relFS)
			if !opts.IncludeGenerated && brain.IsGenerated(logical) {
				return nil
			}
			if opts.Glob != "" {
				matched, _ := filepath.Match(opts.Glob, d.Name())
				if !matched {
					return nil
				}
			}
			fi, infoErr := d.Info()
			if infoErr != nil {
				return infoErr
			}
			entries = append(entries, brain.FileInfo{
				Path:    logical,
				Size:    fi.Size(),
				ModTime: fi.ModTime(),
				IsDir:   false,
			})
			return nil
		})
		if err != nil {
			return nil, err
		}
	} else {
		raw, readErr := os.ReadDir(absDir)
		if readErr != nil {
			return nil, readErr
		}
		for _, d := range raw {
			name := d.Name()
			if d.IsDir() {
				if ShouldSkipDir(name) {
					continue
				}
			} else if ShouldSkipFile(name) {
				continue
			}
			relFS, relErr := filepath.Rel(absRoot, filepath.Join(absDir, name))
			if relErr != nil {
				return nil, relErr
			}
			logical := LogicalFromRel(relFS)
			if !d.IsDir() && !opts.IncludeGenerated && brain.IsGenerated(logical) {
				continue
			}
			if opts.Glob != "" {
				matched, _ := filepath.Match(opts.Glob, name)
				if !matched {
					continue
				}
			}
			fi, infoErr := d.Info()
			if infoErr != nil {
				return nil, infoErr
			}
			entries = append(entries, brain.FileInfo{
				Path:    logical,
				Size:    fi.Size(),
				ModTime: fi.ModTime(),
				IsDir:   d.IsDir(),
			})
		}
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Path < entries[j].Path
	})
	return entries, nil
}
