// SPDX-License-Identifier: Apache-2.0
package ontology

var serverHardwareTemplate = IndustryTemplate{
	Label:       "Server Hardware",
	Description: "Server configuration, components, and compatibility rules",
	NodeTypes: []TypeEntry{
		{Type: "entity.server_model", Label: "Server Model", Description: "A specific model of server hardware"},
		{Type: "entity.component_category", Label: "Component Category", Description: "A category of server components (CPU, Memory, Storage, etc.)"},
		{Type: "entity.component", Label: "Component", Description: "A specific hardware component"},
		{Type: "rule.hardware_compatibility", Label: "Hardware Compatibility", Description: "A compatibility constraint between components"},
		{Type: "rule.configuration_limit", Label: "Configuration Limit", Description: "A maximum or minimum limit on a configuration parameter"},
		{Type: "entity.server_generation", Label: "Server Generation", Description: "A server generation or family (e.g. 13th Gen, 14th Gen PowerEdge)"},
		{Type: "entity.configuration", Label: "Configuration", Description: "A specific hardware configuration combining a server model with selected components"},
		{Type: "rule.hardware_constraint", Label: "Hardware Constraint", Description: "A hard constraint that must be satisfied for a valid server configuration"},
		{Type: "rule.hardware_recommendation", Label: "Hardware Recommendation", Description: "A best-practice recommendation for optimal server configuration"},
	},
	EdgeTypes: []TypeEntry{
		{Type: "compatible_with", Label: "Compatible With", Description: "Indicates hardware compatibility"},
		{Type: "installed_in", Label: "Installed In", Description: "Component installed in a server"},
		{Type: "requires", Label: "Requires", Description: "Component or configuration requires another component or condition"},
		{Type: "incompatible_with", Label: "Incompatible With", Description: "Two components or configurations cannot coexist in the same server"},
		{Type: "recommended_for", Label: "Recommended For", Description: "A component is recommended for a specific server model or configuration"},
		{Type: "applies_to", Label: "Applies To", Description: "A rule or constraint applies to a specific server model, generation, or component category"},
	},
	BusinessCategories: []string{"server_hardware"},
}

var insuranceTemplate = IndustryTemplate{
	Label:       "Insurance",
	Description: "Policies, claims, underwriting rules, and risk assessment",
	NodeTypes: []TypeEntry{
		{Type: "entity.policy", Label: "Policy", Description: "An insurance policy or cover"},
		{Type: "entity.claim", Label: "Claim", Description: "An insurance claim"},
		{Type: "entity.insured_party", Label: "Insured Party", Description: "A person or organisation covered by an insurance policy"},
		{Type: "entity.claimant", Label: "Claimant", Description: "A person or organisation making an insurance claim"},
		{Type: "entity.broker", Label: "Broker", Description: "An insurance broker or intermediary"},
		{Type: "entity.coverage", Label: "Coverage", Description: "A specific type of insurance coverage or protection"},
		{Type: "entity.peril", Label: "Peril", Description: "A specific risk or cause of loss that may be covered"},
		{Type: "entity.endorsement", Label: "Endorsement", Description: "A policy modification or amendment"},
		{Type: "entity.premium", Label: "Premium", Description: "The amount paid for insurance coverage"},
		{Type: "entity.deductible", Label: "Deductible", Description: "The amount the insured must pay before coverage applies"},
		{Type: "entity.risk_object", Label: "Risk Object", Description: "The property, person, or asset being insured"},
		{Type: "entity.underwriter", Label: "Underwriter", Description: "A person or system responsible for policy underwriting"},
		{Type: "entity.beneficiary", Label: "Beneficiary", Description: "A person or organisation entitled to policy benefits"},
		{Type: "rule.underwriting", Label: "Underwriting Rule", Description: "A rule governing policy underwriting decisions"},
		{Type: "rule.claims_assessment", Label: "Claims Assessment", Description: "A rule for assessing claim validity and settlement amount"},
		{Type: "rule.premium_calculation", Label: "Premium Calculation", Description: "A rule for calculating policy premiums based on risk factors"},
		{Type: "rule.coverage_determination", Label: "Coverage Determination", Description: "A rule determining what perils and losses are covered"},
		{Type: "rule.fraud_detection", Label: "Fraud Detection", Description: "A rule for identifying potentially fraudulent claims"},
		{Type: "rule.regulatory_compliance", Label: "Regulatory Compliance", Description: "A regulatory requirement that must be satisfied"},
		{Type: "rule.reserve_setting", Label: "Reserve Setting", Description: "A rule for setting financial reserves for claims"},
	},
	EdgeTypes: []TypeEntry{
		{Type: "covers", Label: "Covers", Description: "Policy covers a risk object or peril"},
		{Type: "filed_against", Label: "Filed Against", Description: "A claim is filed against a specific policy"},
		{Type: "underwrites", Label: "Underwrites", Description: "An underwriter assesses and approves a policy"},
		{Type: "endorses", Label: "Endorses", Description: "An endorsement modifies a policy"},
		{Type: "cedes_to", Label: "Cedes To", Description: "Risk is transferred to a reinsurer"},
		{Type: "adjusts", Label: "Adjusts", Description: "An adjuster assesses a claim"},
		{Type: "pays_out", Label: "Pays Out", Description: "A policy pays benefits to a beneficiary"},
		{Type: "rated_for", Label: "Rated For", Description: "A premium is calculated for a specific risk classification"},
		{Type: "excludes", Label: "Excludes", Description: "A policy explicitly excludes coverage for a specific peril"},
		{Type: "subrogates_against", Label: "Subrogates Against", Description: "An insurer recovers costs from a third party"},
	},
	BusinessCategories: []string{
		"underwriting",
		"claims_management",
		"policy_administration",
		"premium_rating",
		"reinsurance",
		"fraud_prevention",
		"regulatory_compliance",
	},
}

var logisticsTemplate = IndustryTemplate{
	Label:       "Logistics & Supply Chain",
	Description: "Warehousing, transport, routing, and fulfilment rules",
	NodeTypes: []TypeEntry{
		{Type: "entity.trade_item", Label: "Trade Item", Description: "A product or SKU that is traded or shipped"},
		{Type: "entity.logistic_unit", Label: "Logistic Unit", Description: "A packaging unit such as a pallet, carton, or container"},
		{Type: "entity.shipment", Label: "Shipment", Description: "A collection of goods being transported together"},
		{Type: "entity.consignment", Label: "Consignment", Description: "Goods entrusted to a carrier for delivery"},
		{Type: "entity.location", Label: "Location", Description: "A physical location such as a warehouse, depot, or store"},
		{Type: "entity.party", Label: "Party", Description: "An organisation or person involved in logistics operations"},
		{Type: "entity.transport_means", Label: "Transport Means", Description: "A vehicle, vessel, or aircraft used for transportation"},
		{Type: "entity.order", Label: "Order", Description: "A purchase order or sales order requiring fulfilment"},
		{Type: "entity.despatch_advice", Label: "Despatch Advice", Description: "Notification that goods have been dispatched"},
		{Type: "entity.receiving_advice", Label: "Receiving Advice", Description: "Notification that goods have been received"},
		{Type: "entity.bill_of_lading", Label: "Bill of Lading", Description: "A document acknowledging receipt of cargo for shipment"},
		{Type: "entity.customs_declaration", Label: "Customs Declaration", Description: "Documentation for customs clearance of international shipments"},
		{Type: "entity.inventory_position", Label: "Inventory Position", Description: "Stock level at a specific location and point in time"},
		{Type: "process.plan", Label: "Plan", Description: "Demand planning, supply planning, and capacity allocation"},
		{Type: "process.source", Label: "Source", Description: "Procurement and supplier management activities"},
		{Type: "process.make", Label: "Make", Description: "Manufacturing and production activities"},
		{Type: "process.deliver", Label: "Deliver", Description: "Order fulfilment, warehousing, and transportation activities"},
		{Type: "process.return_process", Label: "Return", Description: "Reverse logistics and returns processing"},
		{Type: "process.enable", Label: "Enable", Description: "Support processes such as data management and compliance"},
		{Type: "rule.routing", Label: "Routing Rule", Description: "A rule governing shipment routing and carrier selection"},
		{Type: "rule.capacity", Label: "Capacity Rule", Description: "A rule governing warehouse or vehicle capacity constraints"},
		{Type: "rule.lead_time", Label: "Lead Time", Description: "Expected time required for procurement, production, or delivery"},
		{Type: "rule.reorder_point", Label: "Reorder Point", Description: "Inventory threshold that triggers replenishment"},
		{Type: "rule.carrier_selection", Label: "Carrier Selection", Description: "A rule for selecting carriers based on cost, service level, or constraints"},
		{Type: "rule.hazmat_compliance", Label: "Hazmat Compliance", Description: "A rule governing handling and transport of hazardous materials"},
		{Type: "rule.temperature_control", Label: "Temperature Control", Description: "A rule for maintaining cold chain or controlled temperature"},
		{Type: "rule.customs_regulation", Label: "Customs Regulation", Description: "A customs requirement for international shipments"},
	},
	EdgeTypes: []TypeEntry{
		{Type: "ships_to", Label: "Ships To", Description: "Origin location ships to destination location"},
		{Type: "stored_at", Label: "Stored At", Description: "Trade item or logistic unit stored at a location"},
		{Type: "carried_by", Label: "Carried By", Description: "Shipment or consignment carried by a transport means"},
		{Type: "ordered_by", Label: "Ordered By", Description: "An order is placed by a customer or party"},
		{Type: "supplies", Label: "Supplies", Description: "A supplier provides goods to a customer"},
		{Type: "received_at", Label: "Received At", Description: "Goods received at a location"},
		{Type: "returns_to", Label: "Returns To", Description: "Goods returned to a location or party"},
		{Type: "consolidates", Label: "Consolidates", Description: "Multiple shipments combined into a larger unit"},
		{Type: "deconsolidates", Label: "Deconsolidates", Description: "A shipment is broken down into smaller units"},
		{Type: "cross_docks", Label: "Cross Docks", Description: "Goods transferred directly from inbound to outbound transport"},
		{Type: "customs_cleared_by", Label: "Customs Cleared By", Description: "Shipment cleared through customs by an authority"},
	},
	BusinessCategories: []string{
		"procurement",
		"warehousing",
		"transportation",
		"inventory_management",
		"order_fulfilment",
		"returns_processing",
		"demand_planning",
		"customs_compliance",
	},
}

var financeTemplate = IndustryTemplate{
	Label:       "Finance & Banking",
	Description: "Accounts, transactions, approvals, and compliance rules",
	NodeTypes: []TypeEntry{
		{Type: "entity.account", Label: "Account", Description: "A financial account for deposits, payments, or investments"},
		{Type: "entity.financial_instrument", Label: "Financial Instrument", Description: "A tradable asset such as a bond, equity, or derivative"},
		{Type: "entity.legal_entity", Label: "Legal Entity", Description: "An organisation with legal standing such as a company or trust"},
		{Type: "entity.natural_person", Label: "Natural Person", Description: "An individual human being who is a party to financial transactions"},
		{Type: "entity.currency", Label: "Currency", Description: "A monetary currency such as GBP, USD, or EUR"},
		{Type: "entity.collateral", Label: "Collateral", Description: "Assets pledged as security for a loan or credit facility"},
		{Type: "entity.portfolio", Label: "Portfolio", Description: "A collection of financial instruments held by an investor"},
		{Type: "entity.counterparty", Label: "Counterparty", Description: "The other party to a financial transaction or contract"},
		{Type: "entity.regulator", Label: "Regulator", Description: "A regulatory authority overseeing financial institutions"},
		{Type: "entity.market", Label: "Market", Description: "A financial market where instruments are traded"},
		{Type: "entity.payment", Label: "Payment", Description: "A transfer of funds between accounts or parties"},
		{Type: "entity.credit_facility", Label: "Credit Facility", Description: "A loan, line of credit, or other credit arrangement"},
		{Type: "rule.kyc", Label: "Know Your Customer", Description: "A rule requiring identity verification and due diligence"},
		{Type: "rule.aml", Label: "Anti-Money Laundering", Description: "A rule for detecting and preventing money laundering"},
		{Type: "rule.credit_limit", Label: "Credit Limit", Description: "A maximum amount of credit that may be extended"},
		{Type: "rule.compliance", Label: "Compliance Rule", Description: "A regulatory compliance requirement"},
		{Type: "rule.margin_requirement", Label: "Margin Requirement", Description: "Minimum collateral required to maintain a leveraged position"},
		{Type: "rule.risk_classification", Label: "Risk Classification", Description: "A rule categorising entities or instruments by risk level"},
		{Type: "rule.reporting_obligation", Label: "Reporting Obligation", Description: "A requirement to report transactions or positions to regulators"},
		{Type: "rule.sanctions_screening", Label: "Sanctions Screening", Description: "A rule checking parties against sanctions lists"},
		{Type: "rule.capital_adequacy", Label: "Capital Adequacy", Description: "Minimum capital requirements for financial institutions"},
		{Type: "rule.transaction_limit", Label: "Transaction Limit", Description: "A maximum amount or frequency for transactions"},
	},
	EdgeTypes: []TypeEntry{
		{Type: "authorises", Label: "Authorises", Description: "An approver authorises a transaction or facility"},
		{Type: "subject_to", Label: "Subject To", Description: "An entity is subject to a regulation or requirement"},
		{Type: "issues", Label: "Issues", Description: "A legal entity issues a financial instrument"},
		{Type: "holds", Label: "Holds", Description: "A party holds an account or financial instrument"},
		{Type: "guarantees", Label: "Guarantees", Description: "A party guarantees payment or performance"},
		{Type: "settles", Label: "Settles", Description: "A transaction settles through a settlement system"},
		{Type: "denominates_in", Label: "Denominates In", Description: "An instrument or account is denominated in a currency"},
		{Type: "collateralised_by", Label: "Collateralised By", Description: "A facility is secured by collateral"},
		{Type: "trades_on", Label: "Trades On", Description: "An instrument trades on a specific market"},
		{Type: "regulated_by", Label: "Regulated By", Description: "An entity or market is regulated by an authority"},
		{Type: "beneficial_owner_of", Label: "Beneficial Owner Of", Description: "A natural person has beneficial ownership of an account or entity"},
		{Type: "counterparty_to", Label: "Counterparty To", Description: "A party is counterparty to a transaction or contract"},
	},
	BusinessCategories: []string{
		"retail_banking",
		"commercial_banking",
		"investment_banking",
		"wealth_management",
		"payments",
		"regulatory_compliance",
		"risk_management",
		"trade_lifecycle",
		"credit_management",
	},
}

var healthcareTemplate = IndustryTemplate{
	Label:       "Healthcare",
	Description: "Patients, procedures, medications, and clinical rules",
	NodeTypes: []TypeEntry{
		{Type: "entity.patient", Label: "Patient", Description: "An individual receiving or registered to receive healthcare"},
		{Type: "entity.practitioner", Label: "Practitioner", Description: "A healthcare professional such as a doctor, nurse, or therapist"},
		{Type: "entity.organisation", Label: "Organisation", Description: "A healthcare provider organisation such as a hospital or clinic"},
		{Type: "entity.encounter", Label: "Encounter", Description: "An interaction between a patient and healthcare provider"},
		{Type: "entity.condition", Label: "Condition", Description: "A clinical condition, problem, or diagnosis"},
		{Type: "entity.procedure", Label: "Procedure", Description: "A medical procedure or intervention"},
		{Type: "entity.medication", Label: "Medication", Description: "A pharmaceutical product"},
		{Type: "entity.medication_request", Label: "Medication Request", Description: "A prescription or medication order"},
		{Type: "entity.observation", Label: "Observation", Description: "A clinical observation such as vital signs or lab results"},
		{Type: "entity.diagnostic_report", Label: "Diagnostic Report", Description: "Results of diagnostic investigations such as imaging or pathology"},
		{Type: "entity.allergy_intolerance", Label: "Allergy Intolerance", Description: "A documented allergy or intolerance to a substance"},
		{Type: "entity.immunisation", Label: "Immunisation", Description: "A vaccination record"},
		{Type: "entity.care_plan", Label: "Care Plan", Description: "A plan for delivering coordinated care to a patient"},
		{Type: "entity.care_team", Label: "Care Team", Description: "A group of practitioners responsible for a patient's care"},
		{Type: "entity.claim", Label: "Claim", Description: "A request for payment for healthcare services rendered"},
		{Type: "entity.coverage", Label: "Coverage", Description: "Health insurance coverage or benefit plan"},
		{Type: "entity.device", Label: "Device", Description: "A medical device or implant"},
		{Type: "entity.location", Label: "Location", Description: "A physical location such as a ward, clinic, or operating theatre"},
		{Type: "entity.service_request", Label: "Service Request", Description: "A request for a diagnostic service, referral, or procedure"},
		{Type: "entity.specimen", Label: "Specimen", Description: "A biological sample collected for testing"},
		{Type: "rule.clinical_protocol", Label: "Clinical Protocol", Description: "A rule governing clinical decision-making and treatment pathways"},
		{Type: "rule.contraindication", Label: "Contraindication", Description: "A rule about medication or procedure conflicts"},
		{Type: "rule.dosage_calculation", Label: "Dosage Calculation", Description: "A rule for calculating medication dosage based on patient factors"},
		{Type: "rule.eligibility", Label: "Eligibility", Description: "A rule determining patient eligibility for services or coverage"},
		{Type: "rule.coding_guideline", Label: "Coding Guideline", Description: "A guideline for coding diagnoses and procedures for billing"},
		{Type: "rule.prior_authorisation", Label: "Prior Authorisation", Description: "A requirement for approval before providing services"},
		{Type: "rule.clinical_pathway", Label: "Clinical Pathway", Description: "A standardised care pathway for a specific condition"},
		{Type: "rule.infection_control", Label: "Infection Control", Description: "A protocol for preventing and managing infections"},
		{Type: "rule.discharge_criteria", Label: "Discharge Criteria", Description: "Criteria that must be met before discharging a patient"},
		{Type: "rule.adverse_event", Label: "Adverse Event", Description: "A rule for reporting and managing adverse clinical events"},
	},
	EdgeTypes: []TypeEntry{
		{Type: "treats", Label: "Treats", Description: "A procedure or medication treats a condition"},
		{Type: "diagnoses", Label: "Diagnoses", Description: "A practitioner diagnoses a patient with a condition"},
		{Type: "prescribes", Label: "Prescribes", Description: "A practitioner prescribes medication for a patient"},
		{Type: "contraindicates", Label: "Contraindicates", Description: "A substance or procedure is contraindicated for a condition"},
		{Type: "interacts_with", Label: "Interacts With", Description: "One medication interacts with another medication"},
		{Type: "finding_site", Label: "Finding Site", Description: "A condition or observation has a specific anatomical location"},
		{Type: "has_active_ingredient", Label: "Has Active Ingredient", Description: "A medication contains a specific active pharmaceutical ingredient"},
		{Type: "referred_to", Label: "Referred To", Description: "A patient is referred to a specialist or service"},
		{Type: "resulted_in", Label: "Resulted In", Description: "A procedure or intervention resulted in an outcome or condition"},
		{Type: "caused_by", Label: "Caused By", Description: "A condition is caused by another condition or exposure"},
		{Type: "covered_by", Label: "Covered By", Description: "A service or medication is covered by insurance"},
		{Type: "performed_at", Label: "Performed At", Description: "A procedure or service performed at a location"},
		{Type: "ordered_by", Label: "Ordered By", Description: "A service or medication ordered by a practitioner"},
		{Type: "monitors", Label: "Monitors", Description: "An observation monitors a condition or treatment"},
		{Type: "immunises_against", Label: "Immunises Against", Description: "A vaccination provides immunity against a disease"},
	},
	BusinessCategories: []string{
		"patient_care",
		"clinical_documentation",
		"pharmacy",
		"laboratory",
		"radiology",
		"billing_coding",
		"referral_management",
		"public_health",
		"quality_measurement",
	},
}

var orderProcessingTemplate = IndustryTemplate{
	Label:       "Order Processing",
	Description: "Email order intake, customer matching, product resolution, and ERP integration rules",
	NodeTypes: []TypeEntry{
		{Type: "entity.order", Label: "Order", Description: "A sales order or purchase order being processed"},
		{Type: "entity.erp_system", Label: "ERP System", Description: "An enterprise resource planning system (Business Central, SAP, Zoho, etc.)"},
		{Type: "entity.email_source", Label: "Email Source", Description: "An email inbox or channel that receives order documents"},
		{Type: "rule.order_classification", Label: "Order Classification", Description: "A rule that classifies incoming emails or documents as specific order types"},
		{Type: "rule.customer_matching", Label: "Customer Matching", Description: "A rule for matching order sender to known customers using name, email, or identifiers"},
		{Type: "rule.product_resolution", Label: "Product Resolution", Description: "A rule for resolving product references to SKUs or catalogue items"},
		{Type: "rule.field_mapping", Label: "Field Mapping", Description: "A rule that maps extracted fields to ERP system fields"},
		{Type: "rule.erp_validation", Label: "ERP Validation", Description: "A validation gate that checks data readiness before ERP submission"},
	},
	EdgeTypes: []TypeEntry{
		{Type: "maps_to", Label: "Maps To", Description: "One field or value maps to another in a different system"},
		{Type: "resolves_to", Label: "Resolves To", Description: "An extracted reference resolves to a specific system record"},
		{Type: "submits_to", Label: "Submits To", Description: "Processed data is submitted to an ERP or target system"},
	},
	BusinessCategories: []string{"order_processing"},
}
