# SPDX-License-Identifier: Apache-2.0
"""Memory stages: extract, reflect, consolidate, recall, episodes, buffer."""

from __future__ import annotations

from ._memstore import (
    BatchOptions,
    FileInfo,
    ListOpts,
    MemStore,
    NotFoundError,
    Store,
)
from .consolidate import ConsolidationReport, Consolidator
from .contextualise import (
    Contextualiser,
    ContextualiserConfig,
    apply_contextual_prefix,
    new_contextualiser,
)
from .distill import Distiller, distilled_recall
from .episodes import (
    Episode,
    EpisodeRecorder,
    EpisodeStore,
    InMemoryEpisodeStore,
    should_record_episode,
)
from .extract import (
    EXTRACTION_PROMPT,
    ExtractedMemory,
    Extractor,
    apply_extractions,
    build_manifest,
    build_manifests,
    build_topic_file_content,
    extract_from_messages,
    has_memory_writes,
    parse_extraction_result,
    sanitise_filename,
)
from .heuristic import (
    HeuristicSummary,
    apply_heuristics,
    build_heuristic_content,
    confidence_from_observations,
    has_tag,
    heuristic_filename,
    jaccard_similarity,
    list_heuristics_in,
    merge_heuristic,
    significant_words,
)
from .manager import Memory, MemoryManager
from .paths import (
    base_name,
    brain_root,
    memory_buffer_global,
    memory_buffer_project,
    memory_global_index,
    memory_global_prefix,
    memory_global_topic,
    memory_project_index,
    memory_project_prefix,
    memory_project_topic,
    memory_projects_prefix,
    project_slug,
    set_slug_map_for_test,
)
from .procedural import (
    ProceduralRecord,
    detect_procedurals,
    format_procedural_record,
    infer_procedural_context,
    infer_tool_call_outcome,
)
from .prompt import MEMORY_INSTRUCTIONS
from .recall import (
    RECALL_SELECTOR_PROMPT,
    MAX_RECALL_TOPICS,
    RecallWeights,
    SurfacedMemory,
    date_header,
    format_recalled_memories,
    format_recalled_memories_with_context,
    memory_label,
    parse_selected_memories,
    read_capped_topic,
    recall,
    relative_time_string,
    sort_memories_chronologically,
    topic_age,
)
from .reflect import (
    REFLECTION_SYSTEM_PROMPT,
    Heuristic,
    ReflectionResult,
    Reflector,
    SessionAnalysis,
    analyse_session,
    count_assistant_tool_iterations,
    count_write_tool_calls,
    find_errors,
    find_user_corrections,
    infer_outcome,
    parse_reflection_result,
    should_reflect,
)
from .slugmap import SlugMap
from .store import Frontmatter, TopicFile, parse_frontmatter, parse_kv
from .types import ContentBlock, Message, ToolCall, ToolResultBlock, messages_as_llm
from .wikilink import (
    WIKILINK_PATTERN,
    extract_wikilinks,
    normalise_topic,
    resolve_all_wikilinks,
    resolve_wikilink,
)

__all__ = [
    "BatchOptions",
    "ConsolidationReport",
    "Consolidator",
    "ContentBlock",
    "Contextualiser",
    "ContextualiserConfig",
    "Distiller",
    "EXTRACTION_PROMPT",
    "Episode",
    "EpisodeRecorder",
    "EpisodeStore",
    "ExtractedMemory",
    "Extractor",
    "FileInfo",
    "Frontmatter",
    "Heuristic",
    "HeuristicSummary",
    "InMemoryEpisodeStore",
    "ListOpts",
    "MAX_RECALL_TOPICS",
    "MEMORY_INSTRUCTIONS",
    "MemStore",
    "Memory",
    "MemoryManager",
    "Message",
    "NotFoundError",
    "ProceduralRecord",
    "REFLECTION_SYSTEM_PROMPT",
    "RECALL_SELECTOR_PROMPT",
    "RecallWeights",
    "ReflectionResult",
    "Reflector",
    "SessionAnalysis",
    "SlugMap",
    "Store",
    "SurfacedMemory",
    "ToolCall",
    "ToolResultBlock",
    "TopicFile",
    "WIKILINK_PATTERN",
    "analyse_session",
    "apply_contextual_prefix",
    "apply_extractions",
    "apply_heuristics",
    "base_name",
    "brain_root",
    "build_heuristic_content",
    "build_manifest",
    "build_manifests",
    "build_topic_file_content",
    "confidence_from_observations",
    "count_assistant_tool_iterations",
    "count_write_tool_calls",
    "date_header",
    "detect_procedurals",
    "distilled_recall",
    "extract_from_messages",
    "extract_wikilinks",
    "find_errors",
    "find_user_corrections",
    "format_procedural_record",
    "format_recalled_memories",
    "format_recalled_memories_with_context",
    "has_memory_writes",
    "has_tag",
    "heuristic_filename",
    "infer_outcome",
    "infer_procedural_context",
    "infer_tool_call_outcome",
    "jaccard_similarity",
    "list_heuristics_in",
    "memory_buffer_global",
    "memory_buffer_project",
    "memory_global_index",
    "memory_global_prefix",
    "memory_global_topic",
    "memory_label",
    "memory_project_index",
    "memory_project_prefix",
    "memory_project_topic",
    "memory_projects_prefix",
    "merge_heuristic",
    "messages_as_llm",
    "new_contextualiser",
    "normalise_topic",
    "parse_extraction_result",
    "parse_frontmatter",
    "parse_kv",
    "parse_reflection_result",
    "parse_selected_memories",
    "project_slug",
    "read_capped_topic",
    "recall",
    "relative_time_string",
    "resolve_all_wikilinks",
    "resolve_wikilink",
    "sanitise_filename",
    "set_slug_map_for_test",
    "should_reflect",
    "significant_words",
    "should_record_episode",
    "sort_memories_chronologically",
    "topic_age",
]
