# SPDX-License-Identifier: Apache-2.0
version: "2"
run:
  timeout: 5m
  go: '1.25'
formatters:
  enable:
    - gofmt
    - goimports
linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - misspell
    - unconvert
    - unparam
  settings:
    misspell:
      locale: UK
  exclusions:
    paths:
      - testdata
      - vendor
    rules:
      - path: _test\.go
        linters:
          - unparam
